version: "3"
services:

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "./mosquitto/config/:/mosquitto/config/:ro"

  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - "./telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf"
    depends_on:
      - influxdb

  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - "./influxdb/db:/var/lib/influxdb"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'grafana/env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ./grafana/data:/var/lib/grafana