- hosts: all
  remote_user: ubuntu
  become: yes
  roles:
    - geerlingguy.docker
  vars:
    docker_edition: 'ce'
    docker_install_compose: true
    docker_users:
      - ubuntu
    docker_service_manage: true
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted